// Package store is the data access layer.
//
// Every method that touches user data takes userID as its first argument and
// scopes its SQL by it. That is the whole ownership model: there is no code path
// that reads or writes a row without naming the owner, so a handler cannot
// forget the check. Rows owned by someone else are reported as ErrNotFound
// rather than a permission error, so the API never confirms that an id exists.
package store

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/nls/checkmate/server/internal/patch"
)

// ErrNotFound means no row matched, or the row belongs to another user.
var ErrNotFound = errors.New("store: not found")

// InvalidRefError reports a reference to a row that does not exist or is not
// owned by the caller. Field is the request field to blame, so the HTTP layer
// can return a per-field validation error.
type InvalidRefError struct {
	Field string
	ID    string
}

func (e *InvalidRefError) Error() string {
	return fmt.Sprintf("store: %s %q not found", e.Field, e.ID)
}

// ConflictError reports a request that is well-formed but cannot be applied to
// the current state: a duplicate slug, or a parent that would create a cycle.
type ConflictError struct {
	Field  string
	Detail string
}

func (e *ConflictError) Error() string {
	return fmt.Sprintf("store: %s: %s", e.Field, e.Detail)
}

// Store owns the database handle.
type Store struct {
	db *sql.DB
}

// New wraps db in a Store.
func New(db *sql.DB) *Store { return &Store{db: db} }

// DB exposes the underlying handle for callers that need it (health checks).
func (s *Store) DB() *sql.DB { return s.db }

// querier is the shared subset of *sql.DB and *sql.Tx used by helpers.
type querier interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

// tx runs fn inside a transaction, rolling back on error.
func (s *Store) tx(ctx context.Context, fn func(*sql.Tx) error) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("store: begin: %w", err)
	}
	defer tx.Rollback()

	if err := fn(tx); err != nil {
		return err
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("store: commit: %w", err)
	}

	return nil
}

// nowExpr is the SQL expression for "now" in the format every timestamp column
// uses. Generated by sqlite so all timestamps come from one clock.
const nowExpr = `strftime('%Y-%m-%dT%H:%M:%fZ', 'now')`

// ownedTables maps a request field name to the table its value must exist in.
// Only these tables can be reached by assertOwned, so the table name that ends
// up in SQL is never caller-controlled.
var ownedTables = map[string]string{
	"context_id":      "contexts",
	"project_id":      "projects",
	"parent_id":       "tasks",
	"blocked_by_id":   "tasks",
	"delegated_to_id": "people",
	"recurrence_id":   "recurrences",
}

// assertOwned checks that the row referenced by a request field exists, belongs
// to userID and is not tombstoned. This is what stops a caller attaching their
// task to somebody else's context.
func assertOwned(ctx context.Context, q querier, field, rowID, userID string) error {
	table, ok := ownedTables[field]
	if !ok {
		return fmt.Errorf("store: no owned table for field %q", field)
	}

	return assertRowOwned(ctx, q, table, field, rowID, userID)
}

// assertRowOwned is assertOwned for a table named directly, used when checking
// the target of a request rather than a reference inside its body. table is
// always a package-level literal, never caller input.
func assertRowOwned(ctx context.Context, q querier, table, field, rowID, userID string) error {
	var found int

	err := q.QueryRowContext(ctx,
		`SELECT 1 FROM `+table+` WHERE id = ? AND user_id = ? AND deleted_at IS NULL`,
		rowID, userID,
	).Scan(&found)

	switch {
	case errors.Is(err, sql.ErrNoRows):
		return &InvalidRefError{Field: field, ID: rowID}
	case err != nil:
		return fmt.Errorf("store: verify %s: %w", field, err)
	}

	return nil
}

// assertSourceExists validates a source key against the global lookup.
func assertSourceExists(ctx context.Context, q querier, key string) error {
	var found int

	err := q.QueryRowContext(ctx, `SELECT 1 FROM sources WHERE key = ?`, key).Scan(&found)

	switch {
	case errors.Is(err, sql.ErrNoRows):
		return &InvalidRefError{Field: "source", ID: key}
	case err != nil:
		return fmt.Errorf("store: verify source: %w", err)
	}

	return nil
}

// assertNoCycle walks up the chain formed by column starting at candidate and
// fails if taskID appears, which would make the graph circular. The self-
// reference case is already caught by a CHECK constraint; this catches A -> B -> A.
func assertNoCycle(ctx context.Context, q querier, column, taskID, candidate string) error {
	if column != "parent_id" && column != "blocked_by_id" {
		return fmt.Errorf("store: assertNoCycle: unsupported column %q", column)
	}

	var found int

	err := q.QueryRowContext(ctx, `
		WITH RECURSIVE chain(id) AS (
			SELECT ?
			UNION
			SELECT t.`+column+` FROM tasks t JOIN chain ON t.id = chain.id
			WHERE t.`+column+` IS NOT NULL
		)
		SELECT 1 FROM chain WHERE id = ?`,
		candidate, taskID,
	).Scan(&found)

	switch {
	case errors.Is(err, sql.ErrNoRows):
		return nil
	case err != nil:
		return fmt.Errorf("store: cycle check on %s: %w", column, err)
	}

	return &ConflictError{
		Field:  column,
		Detail: "would create a cycle",
	}
}

// updateBuilder accumulates the SET clause of an UPDATE.
type updateBuilder struct {
	sets []string
	args []any
}

func (b *updateBuilder) set(col string, v any) {
	b.sets = append(b.sets, col+" = ?")
	b.args = append(b.args, v)
}

// setExpr sets a column to a raw SQL expression rather than a bound value.
func (b *updateBuilder) setExpr(col, expr string) {
	b.sets = append(b.sets, col+" = "+expr)
}

func (b *updateBuilder) empty() bool { return len(b.sets) == 0 }

// clause renders "col = ?, col2 = ?" with updated_at appended.
func (b *updateBuilder) clause() string {
	return strings.Join(append(b.sets, "updated_at = "+nowExpr), ", ")
}

// applyField copies a patch field into the builder: absent leaves the column
// alone, null clears it, a value sets it.
func applyField[T any](b *updateBuilder, col string, f patch.Field[T]) {
	if !f.Set {
		return
	}

	if f.Null {
		b.set(col, nil)

		return
	}

	b.set(col, f.Value)
}

// applyBoolField stores a bool as sqlite's 0/1 integer.
func applyBoolField(b *updateBuilder, col string, f patch.Field[bool]) {
	if !f.Set || f.Null {
		return
	}

	b.set(col, boolToInt(f.Value))
}

func boolToInt(v bool) int64 {
	if v {
		return 1
	}

	return 0
}

// listOptions are the paging controls shared by every list endpoint.
type listOptions struct {
	IncludeDeleted bool
	Limit          int
	Cursor         string
}

// DefaultLimit and MaxLimit bound page size.
const (
	DefaultLimit = 50
	MaxLimit     = 200
)

// normalize clamps the limit into range and returns the effective value.
func (o listOptions) normalize() int {
	switch {
	case o.Limit <= 0:
		return DefaultLimit
	case o.Limit > MaxLimit:
		return MaxLimit
	default:
		return o.Limit
	}
}

// conditions accumulates a WHERE clause.
type conditions struct {
	where []string
	args  []any
}

func (c *conditions) add(fragment string, args ...any) {
	c.where = append(c.where, fragment)
	c.args = append(c.args, args...)
}

// addIn appends "col IN (?, ?, ...)" for a non-empty set of values.
func (c *conditions) addIn(col string, values []string) {
	if len(values) == 0 {
		return
	}

	placeholders := make([]string, len(values))
	args := make([]any, len(values))

	for i, v := range values {
		placeholders[i] = "?"
		args[i] = v
	}

	c.add(col+" IN ("+strings.Join(placeholders, ", ")+")", args...)
}

func (c *conditions) clause() string {
	if len(c.where) == 0 {
		return ""
	}

	return " WHERE " + strings.Join(c.where, " AND ")
}

// scanner is satisfied by *sql.Row and *sql.Rows.
type scanner interface {
	Scan(dest ...any) error
}

// notFoundOr maps sql.ErrNoRows onto ErrNotFound and wraps anything else.
func notFoundOr(err error, what string) error {
	if errors.Is(err, sql.ErrNoRows) {
		return ErrNotFound
	}

	return fmt.Errorf("store: %s: %w", what, err)
}
