/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as DoneRouteImport } from './routes/done'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as RepeatingRouteImport } from './routes/repeating'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as WaitingRouteImport } from './routes/waiting'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as SettingsContextsRouteImport } from './routes/settings.contexts'
import { Route as TTaskIdRouteImport } from './routes/t.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const RepeatingRoute = RepeatingRouteImport.update({
  id: '/repeating',
  path: '/repeating',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingRoute = WaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsContextsRoute = SettingsContextsRouteImport.update({
  id: '/contexts',
  path: '/contexts',
  getParentRoute: () => SettingsRoute,
} as any)
const TTaskIdRoute = TTaskIdRouteImport.update({
  id: '/t/$taskId',
  path: '/t/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/blocked': typeof BlockedRoute
  '/done': typeof DoneRoute
  '/inbox': typeof InboxRoute
  '/repeating': typeof RepeatingRoute
  '/routine': typeof RoutineRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signin': typeof SigninRoute
  '/tasks': typeof TasksRoute
  '/waiting': typeof WaitingRoute
  '/c/$slug': typeof CSlugRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/settings/contexts': typeof SettingsContextsRoute
  '/t/$taskId': typeof TTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/blocked': typeof BlockedRoute
  '/done': typeof DoneRoute
  '/inbox': typeof InboxRoute
  '/repeating': typeof RepeatingRoute
  '/routine': typeof RoutineRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signin': typeof SigninRoute
  '/tasks': typeof TasksRoute
  '/waiting': typeof WaitingRoute
  '/c/$slug': typeof CSlugRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/settings/contexts': typeof SettingsContextsRoute
  '/t/$taskId': typeof TTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/blocked': typeof BlockedRoute
  '/done': typeof DoneRoute
  '/inbox': typeof InboxRoute
  '/repeating': typeof RepeatingRoute
  '/routine': typeof RoutineRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signin': typeof SigninRoute
  '/tasks': typeof TasksRoute
  '/waiting': typeof WaitingRoute
  '/c/$slug': typeof CSlugRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/settings/contexts': typeof SettingsContextsRoute
  '/t/$taskId': typeof TTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/blocked'
    | '/done'
    | '/inbox'
    | '/repeating'
    | '/routine'
    | '/settings'
    | '/signin'
    | '/tasks'
    | '/waiting'
    | '/c/$slug'
    | '/p/$projectId'
    | '/settings/contexts'
    | '/t/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/blocked'
    | '/done'
    | '/inbox'
    | '/repeating'
    | '/routine'
    | '/settings'
    | '/signin'
    | '/tasks'
    | '/waiting'
    | '/c/$slug'
    | '/p/$projectId'
    | '/settings/contexts'
    | '/t/$taskId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/blocked'
    | '/done'
    | '/inbox'
    | '/repeating'
    | '/routine'
    | '/settings'
    | '/signin'
    | '/tasks'
    | '/waiting'
    | '/c/$slug'
    | '/p/$projectId'
    | '/settings/contexts'
    | '/t/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BlockedRoute: typeof BlockedRoute
  DoneRoute: typeof DoneRoute
  InboxRoute: typeof InboxRoute
  RepeatingRoute: typeof RepeatingRoute
  RoutineRoute: typeof RoutineRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SigninRoute: typeof SigninRoute
  TasksRoute: typeof TasksRoute
  WaitingRoute: typeof WaitingRoute
  CSlugRoute: typeof CSlugRoute
  PProjectIdRoute: typeof PProjectIdRoute
  TTaskIdRoute: typeof TTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repeating': {
      id: '/repeating'
      path: '/repeating'
      fullPath: '/repeating'
      preLoaderRoute: typeof RepeatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting': {
      id: '/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof WaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/contexts': {
      id: '/settings/contexts'
      path: '/contexts'
      fullPath: '/settings/contexts'
      preLoaderRoute: typeof SettingsContextsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/t/$taskId': {
      id: '/t/$taskId'
      path: '/t/$taskId'
      fullPath: '/t/$taskId'
      preLoaderRoute: typeof TTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsContextsRoute: typeof SettingsContextsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsContextsRoute: SettingsContextsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BlockedRoute: BlockedRoute,
  DoneRoute: DoneRoute,
  InboxRoute: InboxRoute,
  RepeatingRoute: RepeatingRoute,
  RoutineRoute: RoutineRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SigninRoute: SigninRoute,
  TasksRoute: TasksRoute,
  WaitingRoute: WaitingRoute,
  CSlugRoute: CSlugRoute,
  PProjectIdRoute: PProjectIdRoute,
  TTaskIdRoute: TTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
